# 마스터 노드에서 Nginx 배포, LoadBalancer 서비스 구성 및 HPA 설정 플레이북
- name: Configure Nginx Deployment, LoadBalancer Service, and HPA on Master
  hosts: master
  become: yes

  tasks:
    # Nginx 배포를 위한 Deployment YAML 파일 
    - name: Create Nginx Deployment YAML
      copy:
        dest: /root/nginx-deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: project
          spec:
            # replicas 설정 제거 (HPA에 의해 자동 조정)
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: jiruk/project:latest
                  ports:
                  - containerPort: 80
                  resources:
                    requests:
                      cpu: "100m"  # 최소 CPU 요청
                    limits:
                      cpu: "500m"  # 최대 CPU 제한

    # Nginx Deployment을 클러스터에 적용
    - name: Apply Nginx Deployment
      command: kubectl apply -f /root/nginx-deployment.yaml -n project
      register: deploy_output

    # Deployment 적용 결과 출력
    - name: Show Deployment output
      debug:
        var: deploy_output.stdout_lines

    # MetalLB를 위한 Nginx LoadBalancer 서비스 YAML 파일 생성
    - name: Create Nginx LoadBalancer service YAML for MetalLB
      copy:
        dest: /root/nginx-service.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: project
          spec:
            selector:
              app: nginx
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    # LoadBalancer 서비스를 클러스터에 적용
    - name: Apply Nginx LoadBalancer Service
      command: kubectl apply -f /root/nginx-service.yaml -n project
      register: lb_output

    # LoadBalancer 서비스 적용 결과 출력
    - name: Show LoadBalancer service output
      debug:
        var: lb_output.stdout_lines

    # LoadBalancer가 준비될 때까지 대기
    - name: Wait for LoadBalancer to be ready
      command: kubectl get svc nginx-service -n project
      register: svc_check
      retries: 5
      delay: 10
      until: "svc_check.stdout.find('EXTERNAL-IP') != -1"
      ignore_errors: yes

    # Nginx Deployment에 대한 HPA 설정을 위한 YAML 파일 생성
    - name: Create HPA YAML for Nginx Deployment
      copy:
        dest: /root/nginx-hpa.yaml
        content: |
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          metadata:
            name: nginx-hpa
            namespace: project
          spec:
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: nginx-deployment
            minReplicas: 2
            maxReplicas: 10
            metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 50

    # HPA를 클러스터에 적용
    - name: Apply HPA for Nginx Deployment
      command: kubectl apply -f /root/nginx-hpa.yaml -n project
      register: hpa_output

    # HPA 적용 결과 출력
    - name: Show HPA output
      debug:
        var: hpa_output.stdout_lines
