- name: Deploy Nginx on worker nodes
  hosts: workers
  become: yes

  tasks:
    - name: Install Nginx on RedHat-based systems
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Debian-based systems
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure Nginx Deployment and LoadBalancer Service on Master
  hosts: master
  become: yes

  tasks:
    - name: Create ConfigMap for custom index.html
      copy:
        dest: /root/nginx-index-configmap.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: nginx-index-config
            namespace: project
          data:
            index.html: |
              <html>
              <head>
                <title>Project Success</title>
              </head>
              <body>
                <h1 style="color: purple;">Project Success</h1>
              </body>
              </html>

    - name: Apply ConfigMap
      command: kubectl apply -f /root/nginx-index-configmap.yaml -n project
      register: configmap_output

    - name: Show ConfigMap output
      debug:
        var: configmap_output.stdout_lines

    - name: Create Nginx Deployment YAML
      copy:
        dest: /root/nginx-deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: project
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - name: index-html
                    mountPath: /usr/share/nginx/html/index.html
                    subPath: index.html
                volumes:
                - name: index-html
                  configMap:
                    name: nginx-index-config

    - name: Apply Nginx Deployment
      command: kubectl apply -f /root/nginx-deployment.yaml -n project
      register: deploy_output

    - name: Show Deployment output
      debug:
        var: deploy_output.stdout_lines

    - name: Create Nginx LoadBalancer service YAML for MetalLB
      copy:
        dest: /root/nginx-service.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: project 
          spec:
            selector:
              app: nginx
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Apply Nginx LoadBalancer Service
      command: kubectl apply -f /root/nginx-service.yaml -n project
      register: lb_output

    - name: Show LoadBalancer service output
      debug:
        var: lb_output.stdout_lines

    - name: Wait for LoadBalancer to be ready
      command: kubectl get svc nginx-service -n project
      register: svc_check
      retries: 5
      delay: 10
      until: "svc_check.stdout.find('EXTERNAL-IP') != -1"
      ignore_errors: yes
