name: Deploy to Jenkins

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST https://b22b-218-146-17-197.ngrok-free.app/job/project/build \
          --user user1:11762bf4595997335f38d1ba21c685c586
